### ISSUE TITLE
Game Recommendation!

### ISSUE THREAD

**Issue by TrickJoker312** [whyisthesheep/whyisthesheep.github.io#2]
I would appreciate it if you could add the Lofi Funkin mod from Friday Night Funkin!

Here's a link!

https://kbhgames.com/game/friday-night-funkin-lofi-funkin

I would also appreciate a reply!

**Comment by whyisthesheep** [comment]
> I would appreciate it if you could add the Lofi Funkin mod from Friday Night Funkin!
> 
> Here's a link!
> 
> https://kbhgames.com/game/friday-night-funkin-lofi-funkin
> 
> I would also appreciate a reply!

I will consider adding this in the next major update, thanks!

**Comment by TrickJoker312** [comment]
Thank you! I really appreciate it!

[also, when is the next major update?

**Comment by whyisthesheep** [comment]
> Thank you! I really appreciate it!
> 
> [also, when is the next major update?

Not sure but it will be when I have a bunch of new stuff to add
